ERROR - 2024-05-31 03:22:24 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\SIGMarket\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\xampp\htdocs\SIGMarket\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_minimarket', 3306, '', 0)
#1 C:\xampp\htdocs\SIGMarket\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SIGMarket\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SIGMarket\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\SIGMarket\app\Models\ModelSetting.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\SIGMarket\vendor\myth\auth\src\Controllers\AuthController.php(415): App\Models\ModelSetting->DataWeb()
#6 C:\xampp\htdocs\SIGMarket\vendor\myth\auth\src\Controllers\AuthController.php(60): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array)
#7 C:\xampp\htdocs\SIGMarket\system\CodeIgniter.php(902): Myth\Auth\Controllers\AuthController->login()
#8 C:\xampp\htdocs\SIGMarket\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\xampp\htdocs\SIGMarket\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\SIGMarket\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\SIGMarket\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\SIGMarket\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\SIGMarket\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SIGMarket\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SIGMarket\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\SIGMarket\app\Models\ModelSetting.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\SIGMarket\vendor\myth\auth\src\Controllers\AuthController.php(415): App\Models\ModelSetting->DataWeb()
#5 C:\xampp\htdocs\SIGMarket\vendor\myth\auth\src\Controllers\AuthController.php(60): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array)
#6 C:\xampp\htdocs\SIGMarket\system\CodeIgniter.php(902): Myth\Auth\Controllers\AuthController->login()
#7 C:\xampp\htdocs\SIGMarket\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 C:\xampp\htdocs\SIGMarket\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\SIGMarket\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\SIGMarket\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-05-31 03:22:24 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_setting`
WHERE `id` = :id:', [...], false)
 3 APPPATH\Models\ModelSetting.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\myth\auth\src\Controllers\AuthController.php(415): App\Models\ModelSetting->DataWeb()
 5 VENDORPATH\myth\auth\src\Controllers\AuthController.php(60): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth\\login', [...])
 6 SYSTEMPATH\CodeIgniter.php(902): Myth\Auth\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2024-05-31 03:23:48 --> Trying to access array offset on value of type null
in APPPATH\Controllers\Home.php on line 63.
 1 APPPATH\Controllers\Home.php(63): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Controllers\\Home.php', 63)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Home->WilayahToko('highLightTitle.png')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2024-05-31 05:33:31 --> Trying to access array offset on value of type null
in APPPATH\Controllers\Home.php on line 63.
 1 APPPATH\Controllers\Home.php(63): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Controllers\\Home.php', 63)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Home->WilayahToko('highLightTitle.png')
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
